# Stage 1: The cross-compilation environment
FROM debian:trixie AS builder

# Install dependencies for aarch64 cross-compilation
RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    make \
    binutils \
    g++-aarch64-linux-gnu \
    libwebp-dev:arm64 \
    libssl-dev:arm64 \
    zlib1g-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*

# Set up the environment for aarch64 cross-compilation
ENV CROSS_COMPILE=aarch64-linux-gnu-
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig

WORKDIR /usr/src/app

# Copy the entire project context
COPY . .

ARG FIRMWARE_VERSION=dev
RUN make \
    FIRMWARE_VERSION=${FIRMWARE_VERSION} \
    CXX=${CROSS_COMPILE}g++ \
    CC=${CROSS_COMPILE}gcc \
    AR=${CROSS_COMPILE}ar \
    MARCH=armv8-a && \
    ${CROSS_COMPILE}strip tronberry

# Stage 2: Create a minimal final image with only the binary
FROM scratch
COPY --from=builder /usr/src/app/tronberry /tronberry
CMD ["/tronberry"]
